// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obkgmwupowlvrlnbpivp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ia2dtd3Vwb3dsdnJsbmJwaXZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDk2NzIsImV4cCI6MjA2MjEyNTY3Mn0.X79yJ_kURa-MzOF0fKPXZE8YYQmaWHT9eGoixAsTiNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);